version: '3.9'
services:
    nodeapp:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        image: educred/redcolector
        container_name: redcolectorprod
        env_file: 
            - ./.env
        volumes:
            - ./:/home/node/redcolector:ro
        ports:
            - "8080:8080"
        command: npm run start
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_healthy
            es01:
                condition: service_healthy
            es02:
                condition: service_healthy
            kibana:
                condition: service_healthy